// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSXuW0DaOm5I2TQicc5WtptnqxVpvEcqQ',
    appId: '1:811037736619:web:e9fc61badaa31b339c01ee',
    messagingSenderId: '811037736619',
    projectId: 'tiksaver-95178',
    authDomain: 'tiksaver-95178.firebaseapp.com',
    storageBucket: 'tiksaver-95178.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuV5gc-v99CYTZWhBFfT-hDf5mJYrTjYY',
    appId: '1:811037736619:android:7283ed3a09b885919c01ee',
    messagingSenderId: '811037736619',
    projectId: 'tiksaver-95178',
    storageBucket: 'tiksaver-95178.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWjuoPLzrmnbQRM9TPoN6dXN9jj80SC6w',
    appId: '1:811037736619:ios:242e9fb79cdf2fd19c01ee',
    messagingSenderId: '811037736619',
    projectId: 'tiksaver-95178',
    storageBucket: 'tiksaver-95178.firebasestorage.app',
    iosBundleId: 'com.example.tikSaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWjuoPLzrmnbQRM9TPoN6dXN9jj80SC6w',
    appId: '1:811037736619:ios:242e9fb79cdf2fd19c01ee',
    messagingSenderId: '811037736619',
    projectId: 'tiksaver-95178',
    storageBucket: 'tiksaver-95178.firebasestorage.app',
    iosBundleId: 'com.example.tikSaver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSXuW0DaOm5I2TQicc5WtptnqxVpvEcqQ',
    appId: '1:811037736619:web:72862b529fd9cd9a9c01ee',
    messagingSenderId: '811037736619',
    projectId: 'tiksaver-95178',
    authDomain: 'tiksaver-95178.firebaseapp.com',
    storageBucket: 'tiksaver-95178.firebasestorage.app',
  );
}
