name: Flutter CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux runner
    steps:
      - uses: actions/checkout@v4  # Step 1: Check out the code

      - uses: subosito/flutter-action@v2  # Step 2: Set up Flutter environment
        with:
          flutter-version: '3.22.2' # Use your Flutter version
          channel: 'stable'

      - run: flutter pub get  # Step 3: Get Flutter dependencies

      - run: flutter analyze  # Step 4: Analyze the code for warnings/errors

      - run: flutter test  # Step 5: Run tests (optional but recommended)

      - run: flutter build apk --release --target-platform=android-arm64

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1  # Step 7: Use a third-party action to create a release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
