name: Flutter CI/CD

on:
  push:
    branches:
      - main
    tags: # ⭐ NEW: Add a tag trigger
      - 'v*' # Triggers on any tag starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build 64-bit APK
        run: flutter build apk --release --target-platform=android-arm64

      - name: Upload 64-bit APK
        uses: actions/upload-artifact@v4 # ⭐ NEW: Upload the APK as a temporary artifact
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

  create-release: # ⭐ NEW: A separate job to handle the release
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: app-release

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: app-release.apk # ⭐ MODIFIED: Use the downloaded artifact name
          prerelease: false
          body: "Release notes for version ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
